from .node import Node

class QueueLinkedList:
    head: Node | None
    tail: Node | None
    _size: int
    _nomor_urut: int

    def __init__(self) -> None: ...
    def isempty(self) -> bool: ...
    def enqueue(self, nama: str, keluhan: str) -> None: ...
    def dequeue(self) -> Node | None: ...
    def peek(self) -> None: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def display(self) -> None: ...
